.ALIASES
M_M1            M1(d=VOUT g=N03835 s=VIN b=0 ) CN @FIG10_19_NMOS.Fig10_19_NMOS(sch_1):INS3637@BREAKOUT.MbreakN4.Normal(chips)
V_VDD           VDD(+=N03835 -=0 ) CN @FIG10_19_NMOS.Fig10_19_NMOS(sch_1):INS3801@SOURCE.VSRC.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG10_19_NMOS.Fig10_19_NMOS(sch_1):INS3743@SOURCE.VPULSE.Normal(chips)
C_C1            C1(1=VOUT 2=0 ) CN @FIG10_19_NMOS.Fig10_19_NMOS(sch_1):INS3727@ANALOG.C.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
