.ALIASES
V_Vin           Vin(+=VMETAL2 -=0 ) CN @FIG3_10.Fig3_10(sch_1):INS2348@SOURCE.VPULSE.Normal(chips)
C_C12           C12(1=VMETAL2 2=VMETAL1 ) CN @FIG3_10.Fig3_10(sch_1):INS2831@BREAKOUT.Cbreak.Normal(chips)
C_C1sub          C1sub(1=VMETAL1 2=0 ) CN @FIG3_10.Fig3_10(sch_1):INS2860@BREAKOUT.Cbreak.Normal(chips)
R_R1            R1(1=VMETAL1 2=0 ) CN @FIG3_10.Fig3_10(sch_1):INS3006@ANALOG.R.Normal(chips)
_    _(Vmetal1=VMETAL1)
_    _(Vmetal2=VMETAL2)
.ENDALIASES
