.ALIASES
V_Vin           Vin(+=N02512 -=0 ) CN @EX8_14.Ex8_14(sch_1):INS2399@SOURCE.VSRC.Normal(chips)
R_R1            R1(1=N02512 2=N02516 ) CN @EX8_14.Ex8_14(sch_1):INS2432@ANALOG.R.Normal(chips)
C_C1            C1(1=N02516 2=VOUT ) CN @EX8_14.Ex8_14(sch_1):INS2457@ANALOG.C.Normal(chips)
E_E1            E1(3=VOUT 4=0 1=0 2=N02516 ) CN @EX8_14.Ex8_14(sch_1):INS2488@ANALOG.E.Normal(chips)
_    _(Vout=VOUT)
.ENDALIASES
