.ALIASES
V_VDS           VDS(+=N03180 -=0 ) CN @FIG9_33.Fig9_33(sch_1):INS3126@SOURCE.VSRC.Normal(chips)
V_VGS           VGS(+=N03196 -=0 ) CN @FIG9_33.Fig9_33(sch_1):INS3106@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N03180 g=N03196 s=0 b=N03279 ) CN @FIG9_33.Fig9_33(sch_1):INS3074@BREAKOUT.MbreakN4.Normal(chips)
V_VSB           VSB(+=0 -=N03279 ) CN @FIG9_33.Fig9_33(sch_1):INS3255@SOURCE.VSRC.Normal(chips)
.ENDALIASES
