.ALIASES
V_V1            V1(+=N04778 -=0 ) CN @_FIG3_41_MSD.SCHEMATIC1(sch_1):INS4746@SOURCE.VAC.Normal(chips)
L_L1            L1(1=VOUT 2=0 ) CN @_FIG3_41_MSD.SCHEMATIC1(sch_1):INS4674@ANALOG_P.l.Normal(chips)
R_R1            R1(1=N04778 2=VOUT ) CN @_FIG3_41_MSD.SCHEMATIC1(sch_1):INS4654@ANALOG.R.Normal(chips)
C_C1            C1(1=VOUT 2=0 ) CN @_FIG3_41_MSD.SCHEMATIC1(sch_1):INS4694@ANALOG_P.c.Normal(chips)
_    _(Vout=VOUT)
.ENDALIASES
