.ALIASES
I_I1            I1(+=VOUT -=0 ) CN @FIG1_32.Fig1_32(sch_1):INS30@SOURCE.ISRC.Normal(chips)
C_C1            C1(1=0 2=VOUT ) CN @FIG1_32.Fig1_32(sch_1):INS63@ANALOG.C.Normal(chips)
R_R1            R1(1=0 2=VOUT ) CN @FIG1_32.Fig1_32(sch_1):INS88@ANALOG.R.Normal(chips)
L_L1            L1(1=VOUT 2=0 ) CN @FIG1_32.Fig1_32(sch_1):INS113@ANALOG.L.Normal(chips)
_    _(Vout=VOUT)
.ENDALIASES
