.ALIASES
C_C1            C1(1=VOUT 2=0 ) CN @FIG10_14.Fig10_14(sch_1):INS3238@ANALOG.C.Normal(chips)
M_M1            M1(d=VOUT g=N03499 s=VIN b=0 ) CN @FIG10_14.Fig10_14(sch_1):INS3120@BREAKOUT.MbreakN4.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG10_14.Fig10_14(sch_1):INS3256@SOURCE.VPULSE.Normal(chips)
V_VDD           VDD(+=N03499 -=0 ) CN @FIG10_14.Fig10_14(sch_1):INS3400@SOURCE.VSRC.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
