.ALIASES
R_R2            R2(1=VOUT 2=N00779 ) CN @_FIG1_13_MSD.SCHEMATIC1(sch_1):INS699@ANALOG.R.Normal(chips)
R_R3            R3(1=VIN 2=VOUT ) CN @_FIG1_13_MSD.SCHEMATIC1(sch_1):INS719@ANALOG.R.Normal(chips)
R_R1            R1(1=0 2=N00779 ) CN @_FIG1_13_MSD.SCHEMATIC1(sch_1):INS679@ANALOG.R.Normal(chips)
T_T1            T1(A+=VIN A-=0 B+=N00779 B-=0 ) CN @_FIG1_13_MSD.SCHEMATIC1(sch_1):INS649@ANALOG.T.Normal(chips)
V_V1            V1(+=VIN -=0 ) CN @_FIG1_13_MSD.SCHEMATIC1(sch_1):INS917@SOURCE.VSIN.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
