.ALIASES
V_VSG           VSG(+=0 -=N04041 ) CN @FIG9_29_PMOS.Fig9_29(sch_1):INS3933@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N04015 g=N04041 s=0 b=N04132 ) CN @FIG9_29_PMOS.Fig9_29(sch_1):INS3981@BREAKOUT.MbreakP4.Normal(chips)
V_VSD           VSD(+=0 -=N04015 ) CN @FIG9_29_PMOS.Fig9_29(sch_1):INS3957@SOURCE.VSRC.Normal(chips)
V_VBS           VBS(+=N04132 -=0 ) CN @FIG9_29_PMOS.Fig9_29(sch_1):INS4108@SOURCE.VSRC.Normal(chips)
.ENDALIASES
