.ALIASES
R_R1            R1(1=VIN 2=VOUT ) CN @FIG1_22.Fig1_22(sch_1):INS210@ANALOG.R.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG1_22.Fig1_22(sch_1):INS847@SOURCE.VSIN.Normal(chips)
C_C1            C1(1=0 2=VOUT ) CN @FIG1_22.Fig1_22(sch_1):INS1048@ANALOG.C.Normal(chips)
C_C2            C2(1=VIN 2=VOUT ) CN @FIG1_22.Fig1_22(sch_1):INS1199@ANALOG.C.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
