.ALIASES
V_Vin           Vin(+=VIN -=0 ) CN @FIG1_31.Fig1_31(sch_1):INS55@SOURCE.VSRC.Normal(chips)
R_R1            R1(1=N00129 2=VOUT ) CN @FIG1_31.Fig1_31(sch_1):INS88@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=VOUT ) CN @FIG1_31.Fig1_31(sch_1):INS747@ANALOG.R.Normal(chips)
L_L1            L1(1=VOUT 2=0 ) CN @FIG1_31.Fig1_31(sch_1):INS772@ANALOG.L.Normal(chips)
X_U1            U1(1=VIN 2=N00129 ) CN @FIG1_31.Fig1_31(sch_1):INS841@EVAL.Sw_tOpen.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
