.ALIASES
V_VGS           VGS(+=N04108 -=0 ) CN @FIG9_30.Fig9_30(sch_1):INS4010@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N04092 g=N04108 s=0 b=N04068 ) CN @FIG9_30.Fig9_30(sch_1):INS3986@BREAKOUT.MbreakN4.Normal(chips)
V_VDS           VDS(+=N04092 -=0 ) CN @FIG9_30.Fig9_30(sch_1):INS4030@SOURCE.VSRC.Normal(chips)
V_VSB           VSB(+=0 -=N04068 ) CN @FIG9_30.Fig9_30(sch_1):INS4181@SOURCE.VSRC.Normal(chips)
.ENDALIASES
