.ALIASES
V_VDS           VDS(+=N03542 -=0 ) CN @TAB9_1_FTN.Tab9_1_ftn(sch_1):INS3502@SOURCE.VSRC.Normal(chips)
V_VGS           VGS(+=N03536 -=0 ) CN @TAB9_1_FTN.Tab9_1_ftn(sch_1):INS3476@SOURCE.VSRC.Normal(chips)
V_VSB           VSB(+=0 -=N03612 ) CN @TAB9_1_FTN.Tab9_1_ftn(sch_1):INS3586@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N03542 g=N03536 s=0 b=N03612 ) CN @TAB9_1_FTN.Tab9_1_ftn(sch_1):INS3442@BREAKOUT.MbreakN4.Normal(chips)
.ENDALIASES
