.ALIASES
M_M1            M1(d=N00524 g=N00488 s=0 b=N03310 ) CN @FIG9_29.Fig9_29(sch_1):INS30@BREAKOUT.MbreakN4.Normal(chips)
V_VGS           VGS(+=N00488 -=0 ) CN @FIG9_29.Fig9_29(sch_1):INS291@SOURCE.VSRC.Normal(chips)
V_VDS           VDS(+=N00524 -=0 ) CN @FIG9_29.Fig9_29(sch_1):INS339@SOURCE.VSRC.Normal(chips)
V_VSB           VSB(+=0 -=N03310 ) CN @FIG9_29.Fig9_29(sch_1):INS3233@SOURCE.VSRC.Normal(chips)
.ENDALIASES
