.ALIASES
M_M1            M1(d=VOUT g=VIN s=N03176 b=N03176 ) CN
+@FIG10_12_PMOS_LONG.Fig10_12_PMOS_long(sch_1):INS3186@BREAKOUT.MbreakP4.Normal(chips)
C_C1            C1(1=VOUT 2=0 ) CN @FIG10_12_PMOS_LONG.Fig10_12_PMOS_long(sch_1):INS3094@ANALOG.C.Normal(chips)
V_VDD           VDD(+=N03176 -=0 ) CN @FIG10_12_PMOS_LONG.Fig10_12_PMOS_long(sch_1):INS3150@SOURCE.VSRC.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG10_12_PMOS_LONG.Fig10_12_PMOS_long(sch_1):INS3112@SOURCE.VPULSE.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
