.ALIASES
M_M1            M1(d=N04361 g=VDD s=N04482 b=0 ) CN @FIG10_20.Fig10_20(sch_1):INS3954@BREAKOUT.MbreakN4.Normal(chips)
M_M2            M2(d=N04482 g=0 s=N04361 b=VDD ) CN @FIG10_20.Fig10_20(sch_1):INS4217@BREAKOUT.MbreakP4.Normal(chips)
V_Vin           Vin(+=N04361 -=0 ) CN @FIG10_20.Fig10_20(sch_1):INS4275@SOURCE.VPULSE.Normal(chips)
V_VDD           VDD(+=VDD -=0 ) CN @FIG10_20.Fig10_20(sch_1):INS4331@SOURCE.VSRC.Normal(chips)
C_C1            C1(1=N04482 2=0 ) CN @FIG10_20.Fig10_20(sch_1):INS4454@ANALOG.C.Normal(chips)
_    _(VDD=VDD)
.ENDALIASES
