.ALIASES
M_M1            M1(d=N02400 g=N02432 s=0 b=N02905 ) CN @FIG6_13.Fig6_13(sch_1):INS2255@BREAKOUT.MbreakN4.Normal(chips)
V_VGS           VGS(+=N02432 -=0 ) CN @FIG6_13.Fig6_13(sch_1):INS2288@SOURCE.VSRC.Normal(chips)
V_VDS           VDS(+=N02400 -=0 ) CN @FIG6_13.Fig6_13(sch_1):INS2325@SOURCE.VSRC.Normal(chips)
V_VSB           VSB(+=0 -=N02905 ) CN @FIG6_13.Fig6_13(sch_1):INS2790@SOURCE.VSRC.Normal(chips)
.ENDALIASES
