.ALIASES
V_VSG           VSG(+=0 -=N06555 ) CN @TAB9_1_FTP.Tab9_1_ftp(sch_1):INS6479@SOURCE.VSRC.Normal(chips)
V_VSD           VSD(+=0 -=N06561 ) CN @TAB9_1_FTP.Tab9_1_ftp(sch_1):INS6529@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N06561 g=N06555 s=0 b=N06571 ) CN @TAB9_1_FTP.Tab9_1_ftp(sch_1):INS6617@BREAKOUT.MbreakP4.Normal(chips)
V_VBS           VBS(+=N06571 -=0 ) CN @TAB9_1_FTP.Tab9_1_ftp(sch_1):INS6505@SOURCE.VSRC.Normal(chips)
.ENDALIASES
