.ALIASES
V_VSB           VSB(+=0 -=N03501 ) CN @FIG9_34.Fig9_34(sch_1):INS3503@SOURCE.VSRC.Normal(chips)
M_M1            M1(d=N03467 g=N03491 s=0 b=N03501 ) CN @FIG9_34.Fig9_34(sch_1):INS3389@BREAKOUT.MbreakN4.Normal(chips)
V_VDS           VDS(+=N03467 -=0 ) CN @FIG9_34.Fig9_34(sch_1):INS3433@SOURCE.VSRC.Normal(chips)
V_VGS           VGS(+=N03491 -=0 ) CN @FIG9_34.Fig9_34(sch_1):INS3413@SOURCE.VSRC.Normal(chips)
.ENDALIASES
