.ALIASES
M_M1            M1(d=VOUT g=VIN s=0 b=0 ) CN @FIG11_4_LONG.Fig11_4_long(sch_1):INS2287@BREAKOUT.MbreakN4.Normal(chips)
M_M2            M2(d=VOUT g=VIN s=VDD b=VDD ) CN @FIG11_4_LONG.Fig11_4_long(sch_1):INS3150@BREAKOUT.MbreakP4.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG11_4_LONG.Fig11_4_long(sch_1):INS3321@SOURCE.VSRC.Normal(chips)
V_VDD           VDD(+=VDD -=0 ) CN @FIG11_4_LONG.Fig11_4_long(sch_1):INS3345@SOURCE.VSRC.Normal(chips)
_    _(VDD=VDD)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
