.ALIASES
M_M1            M1(d=N00524 g=N00488 s=N02562 b=0 ) CN @FIG9_14.Fig9_14(sch_1):INS30@BREAKOUT.MbreakN4.Normal(chips)
V_Vin           Vin(+=N00488 -=0 ) CN @FIG9_14.Fig9_14(sch_1):INS291@SOURCE.VSRC.Normal(chips)
V_VDD           VDD(+=N00524 -=0 ) CN @FIG9_14.Fig9_14(sch_1):INS339@SOURCE.VSRC.Normal(chips)
R_R1            R1(1=0 2=N02562 ) CN @FIG9_14.Fig9_14(sch_1):INS2467@ANALOG.R.Normal(chips)
.ENDALIASES
