.ALIASES
X_U1            U1(1=VIN 2=N00129 ) CN @FIG1_30.Fig1_30(sch_1):INS26@EVAL.Sw_tClose.Normal(chips)
V_Vin           Vin(+=VIN -=0 ) CN @FIG1_30.Fig1_30(sch_1):INS55@SOURCE.VSRC.Normal(chips)
R_R1            R1(1=N00129 2=VOUT ) CN @FIG1_30.Fig1_30(sch_1):INS88@ANALOG.R.Normal(chips)
C_C1            C1(1=0 2=VOUT ) CN @FIG1_30.Fig1_30(sch_1):INS447@ANALOG.C.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
