.ALIASES
R_R1            R1(1=VIN 2=N00101 ) CN @_FIG3_36_MSD.SCHEMATIC1(sch_1):INS26@ANALOG.R.Normal(chips)
L_L1            L1(1=N00101 2=VOUT ) CN @_FIG3_36_MSD.SCHEMATIC1(sch_1):INS60@ANALOG_P.l.Normal(chips)
C_C1            C1(1=VOUT 2=0 ) CN @_FIG3_36_MSD.SCHEMATIC1(sch_1):INS85@ANALOG_P.c.Normal(chips)
V_V1            V1(+=VIN -=0 ) CN @_FIG3_36_MSD.SCHEMATIC1(sch_1):INS130@SOURCE.VAC.Normal(chips)
_    _(Vin=VIN)
_    _(Vout=VOUT)
.ENDALIASES
