.ALIASES
V_Vplus          Vplus(+=N03309 -=0 ) CN @EX8_18.Ex8_18(sch_1):INS2950@SOURCE.VSRC.Normal(chips)
R_R1            R1(1=N03248 2=VOUT ) CN @EX8_18.Ex8_18(sch_1):INS2974@ANALOG.R.Normal(chips)
E_E1            E1(3=VOUT 4=0 1=N03309 2=N03248 ) CN @EX8_18.Ex8_18(sch_1):INS3010@ANALOG.E.Normal(chips)
C_C1            C1(1=N03248 2=VOUT ) CN @EX8_18.Ex8_18(sch_1):INS2994@ANALOG.C.Normal(chips)
_    _(Vout=VOUT)
.ENDALIASES
